### POST Create a new Deck
POST {{baseUrl}}/api/deck/new

### POST Create a new shuffled Deck
POST {{baseUrl}}/api/deck/new/shuffle

### GET a given Deck by Id
@deckId = ef8bc3d04e9
GET {{baseUrl}}/api/deck/{{deckId}}

### POST Shuffle a given Deck
POST {{baseUrl}}/api/deck/{{deckId}}/shuffle

### GET Draw cards from a given Deck
@count = 3
GET {{baseUrl}}/api/deck/{{deckId}}/draw?count={{count}}}
